models:
  - name: int1_obs_hourly_day_sum
    description: "Aggregated hourly observations at day level per station"
    columns:
      - name: station_date_id
        description: "Surrogate key for station and date"
        tests:
          - unique
          - not_null
      - name: station_id
        description: "Station identifier"
      - name: obs_date
        description: "Date of observation (UTC)"
      - name: avg_temp_c
        description: "Average hourly temperature in Celsius for the day"
      - name: avg_temp_f
        description: "Average hourly temperature in Fahrenheit for the day"
      - name: min_temp_c
        description: "Minimum temperature in Celsius for the day"
      - name: max_temp_c
        description: "Maximum temperature in Celsius for the day"
      - name: avg_dwpt_c
        description: "Average dew point in Celsius"
      - name: avg_dwpt_f
        description: "Average dew point in Fahrenheit"
      - name: avg_rhum_pct
        description: "Average relative humidity (%)"
      - name: avg_air_pressure_hpa
        description: "Average sea-level air pressure (hPa)"
      - name: avg_wind_dir_degrees
        description: "Average wind direction (degrees)"
      - name: avg_wind_speed_km_h
        description: "Average wind speed (km/h)"
      - name: max_wind_peak_gust_km_h
        description: "Max wind gust (km/h)"
      - name: total_precip_mm
        description: "Total precipitation (mm)"
      - name: total_snow_mm
        description: "Total snowfall (mm)"
      - name: total_sunshine_minutes
        description: "Total sunshine duration (minutes)"

  - name: int1_obs_daily_window
    description: "Self-joined 5-day observation window for each station and date"
    columns:
      - name: station_obs_window_id
        description: "Surrogate key for station and anchor observation date"
        tests:
          - unique
          - not_null
      - name: station_id
        description: "Station identifier"
      - name: anchor_date
        description: "Anchor observation date (center of the 5-day window)"
      - name: obs_date
        description: "Actual observation date within the 5-day window"
      - name: tavg_c
        description: "Average daily temperature in Celsius"
      - name: tmin_c
        description: "Minimum daily temperature in Celsius"
      - name: tmax_c
        description: "Maximum daily temperature in Celsius"
      - name: tavg_f
        description: "Average daily temperature in Fahrenheit"
      - name: tmin_f
        description: "Minimum daily temperature in Fahrenheit"
      - name: tmax_f
        description: "Maximum daily temperature in Fahrenheit"
      - name: precipitation_mm
        description: "Total precipitation (mm)"
      - name: snow_mm
        description: "Total snowfall (mm)"
      - name: wind_dir_degrees
        description: "Average wind direction (degrees)"
      - name: wind_speed_km_h
        description: "Average wind speed (km/h)"
      - name: wind_peak_gust_km_h
        description: "Peak gust wind speed (km/h)"
      - name: air_pressure_hpa
        description: "Average sea-level pressure (hPa)"
      - name: sunshine_minutes
        description: "Total sunshine duration in minutes"

  - name: int1_city_coord_and_pop
    description: "Combine city coordinates and population via fuzzy matching constrained by state abbreviations"
    columns:
      - name: city_coord_pop_id
        description: "Surrogate key combining uace and city_pop_id for the matched record"
        tests:
          - unique
          - not_null
      - name: uace
        description: "Unique area code identifier from coordinate data"
      - name: city_pop_id
        description: "Identifier for the matched population record"
      - name: total_matched_chars
        description: "Sum of lengths of tokens matched between coordinate and population names including 'city'"
      - name: matched_token_count
        description: "Count of tokens matched between coordinate and population names including 'city'"
      - name: total_matched_chars_no_city
        description: "Sum of lengths of tokens matched between coordinate and population names excluding 'city'"
      - name: matched_token_count_no_city
        description: "Count of tokens matched between coordinate and population names excluding 'city'"
      - name: pop_city_name
        description: "City name from the population source"
      - name: population_2023
        description: "Population count as of 2023"
      - name: coord_city_name
        description: "City name from the coordinate source"
      - name: area_land_sqm
        description: "Land area of the city in square meters from coordinates"
      - name: area_water_sqm
        description: "Water area of the city in square meters from coordinates"
      - name: latitude
        description: "Latitude of the city centroid from coordinates"
      - name: longitude
        description: "Longitude of the city centroid from coordinates"
